<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\lib\styles.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\styles.css" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
    <ProjectReference Include="..\CBS.Domain\CBS.Domain.csproj" />
    <ProjectReference Include="..\CBS.Infrastructure\CBS.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
  </ItemGroup>

</Project>